Vagrant.configure(2) do |config|
  config.vm.box = "CentOS72"
  config.vm.hostname = "capistrano"
  config.vm.network "private_network", ip: "192.168.100.101"
  config.vm.provision "shell", inline: <<-SHELL
    systemctl restart network.service
    SHELL
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/site.yaml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.limit = 'all'
  end
end
