Vagrant.configure(2) do |config|
  config.vm.box = "CentOS72"
  config.vm.define :hatenabot do | hatenabot |
    hatenabot.vm.hostname = "hatenabot"
    hatenabot.vm.network :private_network, ip: "192.168.100.100"
  end
end
